INSERT INTO INSTRUCTOR (email, first_name, last_name, password, qualification) VALUES ('testins@gmail.com', 'Tom', 'Jerry', 'password', 'MSC')
INSERT INTO INSTRUCTOR (email, first_name, last_name, password, qualification) VALUES ('testins1@gmail.com', 'John', 'Tim', 'password', 'MSC')
INSERT INTO STUDENT (email, first_name, last_name, password, joined_year) VALUES ('teststu@gmail.com', 'Harry', 'Potter', 'password', 2021)
INSERT INTO COURSE (course_name, course_description, status, instructor_id) VALUES ('Arts', 'Study Arts', 'CREATED', 1)
INSERT INTO COURSE (course_name, course_description, status, instructor_id) VALUES ('Maths', 'Study Maths', 'CREATED', 1)
INSERT INTO COURSE (course_name, course_description, status, instructor_id) VALUES ('Science', 'Study Science', 'CREATED', 2)
